[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Posts"
  url = "/post/"
  weight = 20

[[main]]
  name = "Docs"
  url = "/docs/"
  weight = 30

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 40

[[main]]
  name = "Categories"
  url = "/categories"
  weight = 50
