baseURL = "https://hackrole.github.io/"
languageCode = "en-us"
title = "hackrole's note"
theme = "yinwang"
Paginate = 12

[params]
    author = "hackrole"
    github = "hackrole"
    name = "hackrole"
    url = "https://hackrole.github.io/"
    description = "Yet Another Developer"
    menus = true

[[menu.main]]
name = "Home"
url = "/"
weight = 10
[[menu.main]]
name = "Github"
url = "https://github.com/hackrole"
[[menu.main]]
name = "标签"
url = "/tags"
# [[menu.main]]
# name = "about"
# url = "/about"

[[params.social]]
    name = "github"
    url = "https://github.com/hackrole"
[[params.social]]
    name = "twitter"
    url = "https://twitter.com/Daipeng3"
[[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/hackrole"
[params.stye]
    darkestColor = "#d35050"
    darkColor = "#212121"
    lightColor = "#f5e3e0"
    lightestColor = "#f5f5f5"
    primayColor = "#fff"
[taxonomies]
    tag = "tags"
    category = "category"
