#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: post

#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

* emacs                                                              :@emacs:
  all posts in here will have category set to /emacs/

** DONE writing hugo subtree
   CLOSED: [2020-10-28 三 00:20]
   :PROPERTIES:
   :EXPORT_FILE_NAME: subtree-export
   :EXPORT_DATE: 2020-10-29
   :END:

*** first heading within the post
    - this post will be exported as
      =content/posts/writing-hugo-blog-in-org-file-export.md=
    - its title will be "writing Hugo blog in org
    - it will have /hugo/ and /org/ tags and /emacs/ as category
    - the /lastmod/ property in the front-matter is set automatically to the time of export.
    - the menuitem /identifier/ is auto-set
    - the menu item /weight/ and post /weight/ if needed have to be manully specified as show abve.

**** a sub-heading under the heading
    - it's draft state will be marked as =true= because of =#+HUGO_DRAFT: true=.

    with the point_anywhere_, do =C-c C-e H h= to export the whole file titled /Writing Hugo blog in org/to a hugo post.
  
    the exported Markdown has a litter comment footer as set in the /local variables/ section below
  
    it autosave now.
    the title still not correct
    
    try to update something.
    
    #+begin_src ipython :exports both :results result code
      import itertools

      for i in itertools.repeat("Hello world", 3):
          print(i)
      a= "hello world"
      a
    #+end_src

    #+RESULTS:
    #+begin_example
    # Out[34]:
    |    | 0   |
    |----+-----|
    |  0 | h   |
    |  1 | e   |
    |  2 | l   |
    |  3 | l   |
    |  4 | o   |
    |  5 |     |
    |  6 | w   |
    |  7 | o   |
    |  8 | r   |
    |  9 | l   |
    | 10 | d   |
    #+end_example



    
    #+begin_src ipython :session :exports both :results raw :type scalar
      %matplotlib inline
      import matplotlib.pyplot as plt
      import numpy as np
      import pandas as pd
      import seaborn as sns

    #+end_src

      #+RESULTS:
      
#+begin_src python :session :exports both :results raw drawer
  print("hell world")
  print("nice to meet")
#+end_src

#+RESULTS:
:results:
:end:

      

    
* footnotes

* COMMENT Local Variables                                           :ARCHIVE:...


